load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "cartpole",
    srcs = ["cartpole.cc"],
    hdrs = ["cartpole.h"],
    visibility = ["//visibility:public"],
    deps = ["//runtime/sim:env"],
)

cc_test(
    name = "cartpole_test",
    srcs = ["cartpole_test.cc"],
    deps = [
        ":cartpole",
        "@googletest//:gtest_main",
    ],
)
